id: bt0
name: 不太灵
domain: https://www.8bt0.com/
encoding: UTF-8
public: true
render: true
search_type:
    - douban_id
search:
  paths:
  - path: mv/{keyword}.html
    method: get
browse:
  path: tlist.php?sc=1&page={page}
  start: 1
torrents:
  list:
    selector: .picture-container > div.container
  fields:
    title:
      selector: a.torrent-title
    download:
      selector: div.col-md-3:nth-child(4)  > a
      attribute: href
    date_added:
      selector: div.tag-download
    size:
      selector: div.tag-size
    downloadvolumefactor:
      case:
        '*': 0
    uploadvolumefactor:
      case:
        '*': 1
