id: btfox
name: btFox
domain: http://btfox09.top/
encoding: UTF-8
public: true
proxy: true
search:
  paths:
  - path: s?wd={keyword}
    method: get
torrents:
  list:
    selector: div.bodycontent > div.maincontent > div.box_border > div.item > div.box_line > div.threadlist_content
  fields:
    title:
      selector: div.threadlist_subject > div.thread_check > div > a
      attribute: title
    details:
      selector: div.threadlist_subject > div.thread_check > div > a
      attribute: href
    download:
      detail:
        xpath: //textarea[@id="thread_share_text"]/text()
    date_added:
      selector: div.threadlist_note
      filters:
        - name: re_search
          args: [ '(?<=\b date：)\w.+', 0 ]
    size:
      selector: div.threadlist_note
      filters:
        - name: re_search
          args: [ '(?<=\b length：)\w.+?(?= date：)', 0 ]
    downloadvolumefactor:
      case:
        '*': 0
    uploadvolumefactor:
      case:
        '*': 1
