id: btGpt
name: btGpt
domain: https://so.btgpt.net/
encoding: UTF-8
public: true
proxy: true
render: true
referer: search/?kw={keyword}
search:
  paths:
  - path: search/?kw={keyword}
    method: post
torrents:
  list:
    selector: table.table-striped > tbody> tr
  fields:
    title:
      selector: td:nth-child(2)
    download:
      selector: td.text-break > a
      attribute: href
    date_added:
      selector: td:nth-child(4)
    size:
      selector: td:nth-child(3)
