name: NAStool Mac
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - version.py
      - .github/workflows/build-mac.yml
      - requirements.txt

jobs:
  Mac-build:
    runs-on: macos-latest
    steps:
      - name: init Python 3.10.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'
      - name: install dependent packages
        run: |
          python -m pip install --upgrade pip
          pip install wheel numpy==1.23.5 pyparsing==3.0.9 pyinstaller==5.7.0
          git clone --depth=1 -b dev https://github.com/NAStool/nas-tools --recurse-submodule
          cd nas-tools
          pip install -r requirements.txt
          CURRENT_DIR=$(pwd)
          echo ("NASTOOL_CONFIG=$CURRENT_DIR/config/config.yaml") >> $env:GITHUB_ENV
          echo $env:NASTOOL_CONFIG
        shell: bash
      - name: package through pyinstaller
        run: |
          cd nas-tools
          cp ./windows/rely/hook-cn2an.py /Users/runner/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyInstaller/hooks/
          cp ./windows/rely/hook-zhconv.py /Users/runner/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyInstaller/hooks/
          cp ./windows/rely/hook-iso639.py /Users/runner/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/PyInstaller/hooks/
          cp ./third_party.txt ./windows/
          cp ./windows/rely/template.jinja2 /Users/runner/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/setuptools/_vendor/pyparsing/diagram/
          cp -r ./web/. /Users/runner/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/web/
          cp -r ./config/. /Users/runner/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/config/
          cp -r ./db_scripts/. /Users/runner/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/db_scripts/
          cd windows
          pyinstaller nas-tools-mac.spec
        shell: pwsh
      - name: upload mac file
        uses: actions/upload-artifact@v3
        with:
          name: nas-tools
          path: nas-tools/windows/dist/nas-tools